# Generated by Django 4.2.1 on 2023-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0003_alter_tag_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
