# Generated by Django 4.2.1 on 2023-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPEN", "Open"),
                    ("WORKING", "Working"),
                    ("DONE", "Done"),
                    ("OVERDUE", "Overdue"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
