# Generated by Django 4.2.1 on 2023-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0005_alter_todoitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="list.tag"),
        ),
    ]
